import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from '@/context/AuthContext'
import Navbar from '@/components/navigation/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// @ts-ignore
export default function RootLayout({ children }) {
  return (
      <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
      <Navbar/>
      <AuthContextProvider>
        {children}
      </AuthContextProvider>
      </body>
      </html>
  )
}
