import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import Navbar from "@/components/navigation/Navbar";
import getLoggedIn from "@/components/getLoggedIn";
import Footer from "@/components/navigation/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const syne = Syne({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-syne",
});

export const metadata: Metadata = {
  title: "THHS Clubs",
  description: "Generated by create next app",
};

// @ts-ignore
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${syne.variable}`}>
      {/*
        <head /> will contain the components returned by the nearest parent
        head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body className={"min-h-screen relative"}>
        <Navbar />
        <div className={"pb-20"}>
          <AuthContextProvider>{children}</AuthContextProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
