const tagList = [
		{ "value": "club", "label": "Club" },
		{ "value": "academicTeam", "label": "Academic Team" },
		{ "value": "sportsTeam", "label": "Sports Team" },
		{ "value": "stem", "label": "STEM" },
		{ "value": "art", "label": "Art" },
		{ "value": "music", "label": "Music" },
		{ "value": "dance", "label": "Dance" },
		{ "value": "theater", "label": "Theater" },
		{ "value": "communityService", "label": "Community Service" },
		{ "value": "debate", "label": "Debate" },
		{ "value": "cultural", "label": "Cultural" },
		{ "value": "literary", "label": "Literary" },
		{ "value": "environmental", "label": "Environmental" },
		{ "value": "technology", "label": "Technology" },
		{ "value": "science", "label": "Science" },
		{ "value": "mathematics", "label": "Mathematics" },
		{ "value": "popCulture", "label": "Pop Culture" },
		{ "value": "entrepreneurship", "label": "Entrepreneurship" },
		{ "value": "socialJustice", "label": "Social Justice" },
		{ "value": "healthAndWellness", "label": "Health & Wellness" },
		{ "value": "photography", "label": "Photography" },
		{ "value": "journalism", "label": "Journalism" },
		{ "value": "language", "label": "Language" },
		{ "value": "history", "label": "History" },
		{ "value": "volunteer", "label": "Volunteer" },
		{ "value": "leadership", "label": "Leadership" },
		{ "value": "business", "label": "Business" },
		{ "value": "fitness", "label": "Fitness" }
	];

export default tagList